management:
  endpoints:
    web:
      base-path: /

sensedia:
  api-gateway:
    host: ${MANAGER_DEMO}
    client-id: ${CLIENT_ID}
    authorization-key: ${AUTHORIZATION_KEY}
    resources:
      get-payments: /caio-study-api/v1/payments
      oauth: /oauth/access-token
