management:
  endpoints:
    web:
      base-path: /

retry:
  configurations:
    maxAttempts: 4

sensedia:
  api-gateway:
    host: ${API_GATEWAY_DEMO}
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    authorization-key: ${AUTHORIZATION_KEY}
    resources:
      get-pet: /pet-store-api/v3/pet/{petId}
      oauth: /oauth/access-token
      grant-code: /oauth/grant-code
